title:        Ryan Nielson
tagline:      Ryan Nielson
description:  "The personal site and blog of Ryan Nielson."
url:          http://nielson.io
version:      1.1.1
author:
  name:       "Ryan Nielson"
  email:      "ryan.nielson@gmail.com"
markdown:     redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink:    /:year/:month/:title
pygments:     true
paginate:     5
github_username: RyanNielson
twitter_username: RyanNielson
google_analytics: "UA-39338095-2"
disqus_shortname: nielsonio
